%chk=MeOH-esp.chk
%Mem=200GB 
%Nproc=10
#P MP2/aug-cc-pvtz   SP Density=MP2  MaxDisk=500GB

 Generated by TIPTOP/IP_ParmGen.py

0 1 
    O   -0.750870    0.122700    0.000000
    C    0.666540   -0.019470    0.000000
    H    1.031970   -0.543040    0.892100
    H    1.031970   -0.543040   -0.892100
    H    1.074560    0.991200   -0.000000
    H   -1.130800   -0.769940   -0.000000

