%chk=MeOH-opt.chk
%Mem=200GB 
%Nproc=10
#P MP2/6-31G*  IOP(5/13=1)  OPT(MaxCycle=200) MaxDisk=500GB

 Generated by TIPTOP/IP_ParmGen.py

0 1 
    O    0.992200    0.073900    0.072400
    C    0.525500    0.033700   -1.263600
    H    0.885300    0.913400   -1.802900
    H    0.885300   -0.876900   -1.749000
    H   -0.567000    0.033800   -1.258600
    H    1.963900    0.072800    0.035800

