$TINKER89/analyze.x ALAC.xyz amoebabio18.prm EM   
$TINKER89/analyze.x ALAN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ALA.xyz amoebabio18.prm EM
$TINKER89/analyze.x ARGC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ARGN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ARG.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASHC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASHN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASH.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASNC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASNN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASPC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASPN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ASP.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYDC.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYDN.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYD.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYSC.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYSN.xyz amoebabio18.prm EM
$TINKER89/analyze.x CYS.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLHC.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLHN.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLH.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLNC.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLNN.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLN.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLUC.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLUN.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLU.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLYC.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLYN.xyz amoebabio18.prm EM
$TINKER89/analyze.x GLY.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIDC.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIDN.xyz amoebabio18.prm EM
$TINKER89/analyze.x HID.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIEC.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIEN.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIE.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIPC.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIPN.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIP.xyz amoebabio18.prm EM
$TINKER89/analyze.x HISC.xyz amoebabio18.prm EM
$TINKER89/analyze.x HISN.xyz amoebabio18.prm EM
$TINKER89/analyze.x HIS.xyz amoebabio18.prm EM
$TINKER89/analyze.x ILEC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ILEN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ILE.xyz amoebabio18.prm EM
$TINKER89/analyze.x LEUC.xyz amoebabio18.prm EM
$TINKER89/analyze.x LEUN.xyz amoebabio18.prm EM
$TINKER89/analyze.x LEU.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYDC.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYDN.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYD.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYSC.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYSN.xyz amoebabio18.prm EM
$TINKER89/analyze.x LYS.xyz amoebabio18.prm EM
$TINKER89/analyze.x METC.xyz amoebabio18.prm EM
$TINKER89/analyze.x METN.xyz amoebabio18.prm EM
$TINKER89/analyze.x MET.xyz amoebabio18.prm EM
$TINKER89/analyze.x ORNC.xyz amoebabio18.prm EM
$TINKER89/analyze.x ORNN.xyz amoebabio18.prm EM
$TINKER89/analyze.x ORN.xyz amoebabio18.prm EM
$TINKER89/analyze.x PHEC.xyz amoebabio18.prm EM
$TINKER89/analyze.x PHEN.xyz amoebabio18.prm EM
$TINKER89/analyze.x PHE.xyz amoebabio18.prm EM
$TINKER89/analyze.x PROC.xyz amoebabio18.prm EM
$TINKER89/analyze.x PRON.xyz amoebabio18.prm EM
$TINKER89/analyze.x PRO.xyz amoebabio18.prm EM
$TINKER89/analyze.x SERC.xyz amoebabio18.prm EM
$TINKER89/analyze.x SERN.xyz amoebabio18.prm EM
$TINKER89/analyze.x SER.xyz amoebabio18.prm EM
$TINKER89/analyze.x THRC.xyz amoebabio18.prm EM
$TINKER89/analyze.x THRN.xyz amoebabio18.prm EM
$TINKER89/analyze.x THR.xyz amoebabio18.prm EM
$TINKER89/analyze.x TRPC.xyz amoebabio18.prm EM
$TINKER89/analyze.x TRPN.xyz amoebabio18.prm EM
$TINKER89/analyze.x TRP.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYDC.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYDN.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYD.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYRC.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYRN.xyz amoebabio18.prm EM
$TINKER89/analyze.x TYR.xyz amoebabio18.prm EM
$TINKER89/analyze.x VALC.xyz amoebabio18.prm EM
$TINKER89/analyze.x VALN.xyz amoebabio18.prm EM
$TINKER89/analyze.x VAL.xyz amoebabio18.prm EM
